backend:
  name: github
  repo: julianmarmier/julianm-portfolio-netlify
  branch: remodel

media_folder: static/img
public_folder: /img
logo_url: /julianm_logo.svg
site_url: https://julianm.tk/
display_url: https://julianm.tk/

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image"}
  - name: "staticContent"
    label: "Static Content"
    files:
      - { label: "In a Nutshell", name: "intro", widget: "markdown"}
      - { label: "Present", name: "present", widget: "markdown"}
      - label: "Past"
        name: "past"
        label_singular: "Past Experience"
        widget: "list"
        field: { label: "Experience", name: "experience", widget: "markdown" }